---
- name: Create the network configuration file for ethernet interfaces
  ansible.builtin.template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
    mode: 0644
  loop: "{{ network_ether_interfaces }}"
  register: ether_result
  notify: restart networking
