---

- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "kvm >>> create | Call instance creation job"
      ansible.builtin.include_tasks: files/create_vm.yml
      vars:
        vm_name: "mlcl-{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      no_log: "{{ item.no_log | default(True) }}"

    - name: "kvm >>> create | Dump instance config to disk"
      ansible.builtin.copy:
        content: "{{ instance_conf_dict }}"
        dest: "{{ molecule_instance_config }}"
        mode: 0644
